"""Curated English, level-relative screening items. Never generated by an LLM.

v1 is immutable: publish a new version when wording/options/keys change. Attempts
snapshot all private items so deployed revisions cannot change an in-flight test.
"""
import re
import random
from functools import lru_cache
from ..schemas import EducationLevel, ProfileDetails, Question, Option

VERSION = 'student-calibration-v1'


def q(key, dimension, prompt, options, correct, difficulty=0.5):
    choices = [Option(id=chr(97 + index), text=text) for index, text in enumerate(options)]
    return Question(id=key, dimension=dimension, prompt=prompt, options=choices,
                    correct_option_id=choices[correct].id, difficulty=difficulty,
                    kind='true_false' if options == ['True', 'False'] else 'mcq')


@lru_cache(maxsize=1)
def banks():
    # Two items per dimension. Scientific reasoning/problem-solving is spread
    # across reasoning and domain items, not treated as curriculum mastery.
    result = {
        'primary': [
            q('p-r1', 'reasoning', 'The pattern is circle, square, circle, square. What comes next?', ['Circle', 'Square', 'Triangle'], 0, .25),
            q('p-r2', 'reasoning', 'Mia is taller than Leo. Leo is taller than Sam. Who is tallest?', ['Sam', 'Leo', 'Mia'], 2, .45),
            q('p-q1', 'quantitative', 'You have 8 crayons and give away 3. How many are left?', ['3', '5', '11'], 1, .3),
            q('p-q2', 'quantitative', 'Twelve stickers are shared equally by 3 children. Each gets:', ['3', '4', '6'], 1, .55),
            q('p-c1', 'comprehension', 'Ava took an umbrella because rain was forecast. Why did she take it?', ['To stay dry', 'To carry lunch', 'To tell the time'], 0, .25),
            q('p-c2', 'comprehension', 'Ben planted a seed. He watered it each day. A shoot appeared. What happened first?', ['A shoot appeared', 'Ben watered it', 'Ben planted a seed'], 2, .4),
            q('p-d1', 'domain_familiarity', 'Which would help you find out whether a plant grows taller?', ['Measure its height each week', 'Change its name', 'Count its pot colours'], 0, .4),
            q('p-d2', 'domain_familiarity', 'You want to see which paper towel absorbs more water. Use the same amount of water for each towel.', ['True', 'False'], 0, .5),
        ],
        'middle_school': [
            q('m-r1', 'reasoning', 'Every member of Club A wears a badge. Jo is in Club A. What must be true?', ['Jo wears a badge', 'Everyone with a badge is in Club A', 'Jo leads Club A'], 0, .35),
            q('m-r2', 'reasoning', 'The sequence is 3, 6, 12, 24. What comes next?', ['30', '36', '48'], 2, .5),
            q('m-q1', 'quantitative', 'A $20 book has a 25% discount. What is the new price?', ['$5', '$15', '$18'], 1, .5),
            q('m-q2', 'quantitative', 'A drink uses juice and water in a 1:3 ratio. With 2 cups of juice, how much water is needed?', ['3 cups', '5 cups', '6 cups'], 2, .6),
            q('m-c1', 'comprehension', 'The library extended its hours, but attendance did not rise. Which statement is supported?', ['Longer hours guaranteed more visitors', 'Attendance did not increase', 'The library closed'], 1, .4),
            q('m-c2', 'comprehension', 'A report says some birds migrate, while others stay year-round. Which summary is best?', ['All birds migrate', 'No birds migrate', 'Migration varies among birds'], 2, .45),
            q('m-d1', 'domain_familiarity', 'To test whether light affects seedling growth, what should differ between the groups?', ['Only their light exposure', 'Light, water, and seed type', 'Everything'], 0, .55),
            q('m-d2', 'domain_familiarity', 'A claim is supported by repeated measurements from several trials. This is stronger evidence than one guess.', ['True', 'False'], 0, .35),
        ],
        'high_school': [
            q('h-r1', 'reasoning', 'If a device overheats, it shuts down. It has not shut down. Assuming the rule holds, what follows?', ['It did not overheat', 'It overheated', 'It is unplugged'], 0, .6),
            q('h-r2', 'reasoning', 'Ice-cream sales and swimming accidents rise in summer. Does this alone show ice cream causes accidents?', ['Yes', 'No; a shared factor could explain both', 'Only if sales double'], 1, .5),
            q('h-q1', 'quantitative', 'Solve 3x + 5 = 20.', ['x = 5', 'x = 8', 'x = 15'], 0, .45),
            q('h-q2', 'quantitative', 'A bag has 3 red and 2 blue balls. One is picked randomly. What is the probability of blue?', ['1/2', '2/5', '2/3'], 1, .55),
            q('h-c1', 'comprehension', 'A study found improved recall after sleep, but only tested 20 adults. Which conclusion is most careful?', ['Sleep improves recall in every person', 'The sample suggests an effect; broader testing is needed', 'Sleep has no effect'], 1, .55),
            q('h-c2', 'comprehension', 'Although the plan costs more initially, it reduces annual running costs. What trade-off is described?', ['Lower starting cost and higher running cost', 'Higher starting cost and lower running cost', 'No costs'], 1, .4),
            q('h-d1', 'domain_familiarity', 'Why repeat an experiment?', ['To assess consistency and reduce chance effects', 'To guarantee the desired result', 'To remove the need for controls'], 0, .45),
            q('h-d2', 'domain_familiarity', 'Which observation best tests a claim that fertilizer increases growth?', ['One treated plant photographed once', 'Growth in comparable treated and untreated groups', 'The price of fertilizer'], 1, .6),
        ],
        'college': [
            q('i-r1', 'reasoning', 'All valid submissions include a signature. This submission has a signature. Is it necessarily valid?', ['Yes', 'No; a signature is necessary but not sufficient', 'It must be invalid'], 1, .6),
            q('i-r2', 'reasoning', 'Two explanations predict the same result. Which next step best distinguishes them?', ['Repeat the shared prediction only', 'Test a case where their predictions differ', 'Choose the simpler wording'], 1, .65),
            q('i-q1', 'quantitative', 'A value rises from 80 to 100. What is the percentage increase?', ['20%', '25%', '80%'], 1, .5),
            q('i-q2', 'quantitative', 'A fair coin is tossed twice. What is the probability of two heads?', ['1/4', '1/2', '3/4'], 0, .6),
            q('i-c1', 'comprehension', 'The policy reduced waste in cities with reliable collection; effects elsewhere are unknown. What is the limitation?', ['The findings may not generalize to other collection systems', 'The policy increased all waste', 'No cities were studied'], 0, .5),
            q('i-c2', 'comprehension', 'A writer argues that access is necessary for participation but does not ensure participation. Which paraphrase is accurate?', ['Access guarantees participation', 'Participation requires access, plus possibly other conditions', 'Access prevents participation'], 1, .6),
            q('i-d1', 'domain_familiarity', 'A survey recruits only volunteers from a science club. What most limits conclusions about all students?', ['Selection bias', 'A large font', 'Using a questionnaire'], 0, .6),
            q('i-d2', 'domain_familiarity', 'In a comparison study, a control group provides:', ['A reference for assessing the intervention', 'Proof before any measurement', 'A way to exclude unexpected results'], 0, .5),
        ],
        'undergraduate': [
            q('u-r1', 'reasoning', 'A diagnostic test is positive. The condition is rare and false positives occur. Which is essential for interpreting the result?', ['The base rate and test accuracy', 'Only the positive result', 'The name of the test'], 0, .65),
            q('u-r2', 'reasoning', 'A successful prediction agrees with a hypothesis. Why is this not definitive proof?', ['Alternative hypotheses may predict the same result', 'Predictions cannot be tested', 'Agreement always disproves it'], 0, .65),
            q('u-q1', 'quantitative', 'Scores are 4, 5, 6, 7, and 100. Which better represents a typical score when an outlier is present?', ['Mean', 'Median', 'Maximum'], 1, .55),
            q('u-q2', 'quantitative', 'Risk falls from 10% to 5%. What is the absolute reduction?', ['5 percentage points', '50 percentage points', '2 percentage points'], 0, .6),
            q('u-c1', 'comprehension', 'An analysis finds an association after adjusting for measured factors, but unmeasured confounding remains possible. What is justified?', ['Causation is proven', 'An adjusted association with a remaining limitation', 'There is no association'], 1, .65),
            q('u-c2', 'comprehension', 'A review says the evidence is promising but heterogeneous in methods and outcomes. What does heterogeneous mean here?', ['The studies differ in important ways', 'All studies are identical', 'Every study is incorrect'], 0, .55),
            q('u-d1', 'domain_familiarity', 'Why preregister an analysis plan?', ['To distinguish planned tests from decisions made after seeing results', 'To guarantee statistical significance', 'To avoid collecting data'], 0, .65),
            q('u-d2', 'domain_familiarity', 'Which most directly strengthens causal inference in an intervention study?', ['Random assignment when ethical and feasible', 'A persuasive title', 'Reporting only favorable outcomes'], 0, .6),
        ],
        'graduate': [
            q('g-r1', 'reasoning', 'A model fits training data extremely well but performs poorly on new data. Which explanation is most plausible?', ['Overfitting', 'Guaranteed generalization', 'New data cannot be evaluated'], 0, .6),
            q('g-r2', 'reasoning', 'An estimated effect reverses after stratifying by a relevant variable. What should be examined first?', ['Confounding and group composition', 'Whether to discard inconvenient groups', 'Only the pooled average'], 0, .7),
            q('g-q1', 'quantitative', 'A 95% confidence interval for a difference is [-2, 5]. Which statement is justified?', ['The interval excludes zero', 'The interval includes both negative and positive differences', 'The effect is certainly positive'], 1, .65),
            q('g-q2', 'quantitative', 'A sample size is quadrupled under the same independent sampling assumptions. Standard error is approximately:', ['Halved', 'Doubled', 'Unchanged'], 0, .75),
            q('g-c1', 'comprehension', 'The paper distinguishes absence of evidence from evidence of absence. What is the point?', ['A null finding alone may not establish that no effect exists', 'Every null result proves an effect', 'All evidence is equivalent'], 0, .65),
            q('g-c2', 'comprehension', 'An author calls an explanation parsimonious but notes weak identification. Which summary is accurate?', ['It is simple, but the data may not uniquely support it', 'It is complex and proven', 'It needs no evidence'], 0, .7),
            q('g-d1', 'domain_familiarity', 'A robustness analysis asks whether a result persists under reasonable alternative assumptions.', ['True', 'False'], 0, .55),
            q('g-d2', 'domain_familiarity', 'Which is strongest support for a claim of generalizability?', ['Independent validation in relevant new populations', 'More decimal places in the original result', 'A larger title'], 0, .7),
        ],
        'other': [
            q('o-r1', 'reasoning', 'A shop is closed every Monday. Today it is open. Assuming the rule holds, today is:', ['Definitely Monday', 'Not Monday', 'Definitely Tuesday'], 1, .4),
            q('o-r2', 'reasoning', 'A phone stopped charging after a cable change. What is the best first check?', ['Test another known-working cable', 'Assume the phone is broken', 'Replace every device'], 0, .4),
            q('o-q1', 'quantitative', 'Three items cost $4 each. What is the total?', ['$7', '$12', '$16'], 1, .35),
            q('o-q2', 'quantitative', 'A recipe for 2 people uses 1 cup of rice. For 6 people at the same ratio, use:', ['2 cups', '3 cups', '6 cups'], 1, .5),
            q('o-c1', 'comprehension', 'The notice says applications received after Friday may be delayed. What does it say?', ['Late applications are always rejected', 'Late applications could take longer', 'Friday applications are impossible'], 1, .4),
            q('o-c2', 'comprehension', 'The guide recommends checking the source before sharing a claim. What is the recommended action?', ['Share first', 'Verify the source first', 'Count the likes only'], 1, .3),
            q('o-d1', 'domain_familiarity', 'Which best supports a claim about average travel time?', ['Timing several comparable trips', 'Guessing from one photo', 'Choosing the most convenient number'], 0, .4),
            q('o-d2', 'domain_familiarity', 'Testing one change at a time can help identify what caused a difference.', ['True', 'False'], 0, .45),
        ],
    }
    for level in EducationLevel:
        items = result[level.value]
        assert len(items) == 8 and len({item.id for item in items}) == 8
        assert all(sum(item.dimension == dim for item in items) == 2 for dim in ('reasoning', 'quantitative', 'comprehension', 'domain_familiarity'))
    return result


def field_domain(field):
    patterns = {
        'computing': r'\b(computer|computing|software|programming|informatics|data science)\b',
        'health': r'\b(medicine|medical|nursing|health|pharmacy|dentistry)\b',
        'business': r'\b(business|commerce|finance|accounting|economics|management)\b',
        'humanities': r'\b(history|literature|language|philosophy|humanities|law|arts)\b',
        'stem': r'\b(science|physics|chemistry|biology|engineering|mathematics|maths|math)\b',
    }
    return next((domain for domain, pattern in patterns.items() if re.search(pattern, field, re.I)), 'general')


def blueprint(details: ProfileDetails, seed: str | None = None):
    from .domains import domain_questions
    level = details.education_level.value
    domain = field_domain(details.field_of_study) if level in {'high_school', 'college', 'undergraduate', 'graduate'} else 'general'
    items = [item.model_copy(deep=True) for item in banks()[level]]
    if domain != 'general':
        items[-2:] = domain_questions(level, domain)
    if seed is not None:
        rng = random.Random(seed)
        for item in items:
            answer = item.correct_option_id
            rng.shuffle(item.options)
            for index, option in enumerate(item.options):
                was_correct = option.id == answer
                option.id = chr(97 + index)
                if was_correct:
                    item.correct_option_id = option.id
    return f'{VERSION}/{level}/{domain}', items
