"""Capability-specific provider contracts, independent of consuming features."""
from pathlib import Path
from typing import Protocol


class ImageOCR(Protocol):
    def available(self) -> bool: ...
    def supported_formats(self) -> tuple[str, ...]: ...
    def extract_text(self, path: Path) -> str: ...
    def asset_revisions(self) -> tuple[tuple[str, str], ...]: ...


class PDFPageRasterizer(Protocol):
    def available(self) -> bool: ...
    def render_page(self, path: Path, page: int, output: Path) -> None: ...
    def asset_revisions(self) -> tuple[tuple[str, str], ...]: ...
