"""Initial PostgreSQL learner and identity schema

Revision ID: 20261007_0001
Revises:
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '20261007_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name=op.f('ck_concept_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept')),
    sa.UniqueConstraint('normalized_name', name=op.f('uq_concept_normalized_name'))
    )
    op.create_table('learner',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner'))
    )
    op.create_table('concept_alias',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('normalized_alias', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_concept_alias_confidence')),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name=op.f('fk_concept_alias_concept_id_concept')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_alias')),
    sa.UniqueConstraint('concept_id', 'normalized_alias', name=op.f('uq_concept_alias_concept_id'))
    )
    op.create_index('idx_concept_alias_normalized', 'concept_alias', ['normalized_alias'], unique=False)
    op.create_table('concept_redirect',
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_id != target_id', name=op.f('ck_concept_redirect_distinct_concepts')),
    sa.ForeignKeyConstraint(['source_id'], ['concept.id'], name=op.f('fk_concept_redirect_source_id_concept')),
    sa.ForeignKeyConstraint(['target_id'], ['concept.id'], name=op.f('fk_concept_redirect_target_id_concept')),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_concept_redirect'))
    )
    op.create_index('idx_redirect_target', 'concept_redirect', ['target_id'], unique=False)
    op.create_table('concept_relation',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_concept_id', sa.Text(), nullable=False),
    sa.Column('target_concept_id', sa.Text(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relation_type IN ('PARENT_OF','PREREQUISITE_OF','RELATED_TO')", name=op.f('ck_concept_relation_type')),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_concept_relation_confidence')),
    sa.CheckConstraint('source_concept_id != target_concept_id', name=op.f('ck_concept_relation_distinct_concepts')),
    sa.ForeignKeyConstraint(['source_concept_id'], ['concept.id'], name=op.f('fk_concept_relation_source_concept_id_concept')),
    sa.ForeignKeyConstraint(['target_concept_id'], ['concept.id'], name=op.f('fk_concept_relation_target_concept_id_concept')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_relation')),
    sa.UniqueConstraint('source_concept_id', 'target_concept_id', 'relation_type', name=op.f('uq_concept_relation_source_concept_id'))
    )
    op.create_index('idx_concept_relation_source', 'concept_relation', ['source_concept_id', 'relation_type'], unique=False)
    op.create_index('idx_concept_relation_target', 'concept_relation', ['target_concept_id', 'relation_type'], unique=False)
    op.create_table('external_identity',
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('external_subject_id', sa.Text(), nullable=False),
    sa.Column('learner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(provider) BETWEEN 1 AND 64 AND length(external_subject_id) BETWEEN 1 AND 300', name=op.f('ck_external_identity_identity')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_external_identity_learner_id_learner')),
    sa.PrimaryKeyConstraint('provider', 'external_subject_id', name=op.f('pk_external_identity'))
    )
    op.create_index('idx_external_identity_learner', 'external_identity', ['learner_id'], unique=False)
    op.create_table('learner_audit',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('learner_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('concept_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name=op.f('fk_learner_audit_concept_id_concept')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_learner_audit_learner_id_learner')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_audit'))
    )
    op.create_index('idx_learner_audit_subject', 'learner_audit', ['learner_id', 'concept_id', 'id'], unique=False)
    op.create_table('learner_concept_state',
    sa.Column('learner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=False),
    sa.Column('mastery', sa.Double(), nullable=True),
    sa.Column('estimate_confidence', sa.Double(), nullable=True),
    sa.Column('retention_confidence', sa.Double(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('independent_successes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hint_dependency', sa.Double(), nullable=True),
    sa.Column('difficulty_tested', sa.Double(), nullable=True),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_demonstrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('policy_data_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('mastery_policy_version', sa.Text(), server_default='legacy', nullable=False),
    sa.Column('retention_policy_version', sa.Text(), server_default='legacy', nullable=False),
    sa.Column('verification_required', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('difficulty_tested BETWEEN 0 AND 1', name=op.f('ck_learner_concept_state_difficulty_tested')),
    sa.CheckConstraint('estimate_confidence BETWEEN 0 AND 1', name=op.f('ck_learner_concept_state_estimate_confidence')),
    sa.CheckConstraint('evidence_count >= 0 AND independent_successes >= 0', name=op.f('ck_learner_concept_state_counts')),
    sa.CheckConstraint('hint_dependency BETWEEN 0 AND 1', name=op.f('ck_learner_concept_state_hint_dependency')),
    sa.CheckConstraint('mastery BETWEEN 0 AND 1', name=op.f('ck_learner_concept_state_mastery')),
    sa.CheckConstraint('retention_confidence BETWEEN 0 AND 1', name=op.f('ck_learner_concept_state_retention_confidence')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_learner_concept_state_version')),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name=op.f('fk_learner_concept_state_concept_id_concept')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_learner_concept_state_learner_id_learner')),
    sa.PrimaryKeyConstraint('learner_id', 'concept_id', name=op.f('pk_learner_concept_state'))
    )
    op.create_index('idx_learner_state_learner', 'learner_concept_state', ['learner_id', 'updated_at'], unique=False)
    op.create_table('learning_context',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('learner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dormant_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','RELATED','DORMANT','ARCHIVED')", name=op.f('ck_learning_context_status')),
    sa.CheckConstraint('relevance_score BETWEEN 0 AND 1', name=op.f('ck_learning_context_relevance')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_learning_context_learner_id_learner')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_context')),
    sa.UniqueConstraint('learner_id', 'id', name='uq_learning_context_learner_identity'),
    sa.UniqueConstraint('learner_id', 'normalized_name', name='uq_learning_context_learner_name')
    )
    op.create_index('idx_learning_context_learner_status', 'learning_context', ['learner_id', 'status', 'last_activity_at'], unique=False)
    op.create_table('mentra_account',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('learner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(username) BETWEEN 3 AND 64 AND username = lower(username)', name=op.f('ck_mentra_account_username')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_mentra_account_learner_id_learner')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_mentra_account')),
    sa.UniqueConstraint('learner_id', 'user_id', name='uq_mentra_account_owner'),
    sa.UniqueConstraint('learner_id', name=op.f('uq_mentra_account_learner_id')),
    sa.UniqueConstraint('username', name=op.f('uq_mentra_account_username'))
    )
    op.create_table('auth_session',
    sa.Column('session_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('token_digest', sa.Text(), nullable=False),
    sa.Column('learner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL AND provider IS NULL) OR (user_id IS NULL AND provider IS NOT NULL)', name=op.f('ck_auth_session_origin')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_auth_session_expiry')),
    sa.CheckConstraint('length(token_digest) = 64', name=op.f('ck_auth_session_digest')),
    sa.ForeignKeyConstraint(['learner_id', 'user_id'], ['mentra_account.learner_id', 'mentra_account.user_id'], name=op.f('fk_auth_session_learner_id_mentra_account')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_auth_session_learner_id_learner')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_auth_session')),
    sa.UniqueConstraint('token_digest', name=op.f('uq_auth_session_token_digest'))
    )
    op.create_index('idx_auth_session_expiry', 'auth_session', ['expires_at'], unique=False)
    op.create_index('idx_auth_session_learner', 'auth_session', ['learner_id'], unique=False)
    op.create_table('candidate_concept',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('proposed_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('learner_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('context_id', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('resolution_status', sa.Text(), server_default='UNRESOLVED', nullable=False),
    sa.Column('resolved_concept_id', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("resolution_status IN ('UNRESOLVED','PROMOTED','MERGED','DISCARDED')", name=op.f('ck_candidate_concept_status')),
    sa.CheckConstraint('context_id IS NULL OR learner_id IS NOT NULL', name=op.f('ck_candidate_concept_owner_scope')),
    sa.CheckConstraint('occurrence_count > 0', name=op.f('ck_candidate_concept_occurrence_count')),
    sa.ForeignKeyConstraint(['learner_id', 'context_id'], ['learning_context.learner_id', 'learning_context.id'], name=op.f('fk_candidate_concept_learner_id_learning_context')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_candidate_concept_learner_id_learner')),
    sa.ForeignKeyConstraint(['resolved_concept_id'], ['concept.id'], name=op.f('fk_candidate_concept_resolved_concept_id_concept')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_concept'))
    )
    op.create_index('uq_candidate_concept_name_context', 'candidate_concept', ['learner_id', 'normalized_name', sa.literal_column("coalesce(context_id, '')")], unique=True, postgresql_where=sa.text('learner_id IS NOT NULL'))
    op.create_index('uq_candidate_concept_global_name', 'candidate_concept', ['normalized_name'], unique=True, postgresql_where=sa.text('learner_id IS NULL'))
    op.create_table('context_concept',
    sa.Column('context_id', sa.Text(), nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=False),
    sa.Column('learner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('importance', sa.Double(), server_default='0.5', nullable=False),
    sa.Column('target_difficulty', sa.Double(), server_default='0.5', nullable=False),
    sa.CheckConstraint('importance BETWEEN 0 AND 1', name=op.f('ck_context_concept_importance')),
    sa.CheckConstraint('target_difficulty BETWEEN 0 AND 1', name=op.f('ck_context_concept_target_difficulty')),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name=op.f('fk_context_concept_concept_id_concept')),
    sa.ForeignKeyConstraint(['learner_id', 'context_id'], ['learning_context.learner_id', 'learning_context.id'], name=op.f('fk_context_concept_learner_id_learning_context')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_context_concept_learner_id_learner')),
    sa.PrimaryKeyConstraint('context_id', 'concept_id', name=op.f('pk_context_concept'))
    )
    op.create_index('idx_context_concept_concept', 'context_concept', ['concept_id', 'context_id'], unique=False)
    op.create_index('idx_context_concept_learner', 'context_concept', ['learner_id', 'concept_id'], unique=False)
    op.create_table('learning_evidence',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('learner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=False),
    sa.Column('context_id', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('score', sa.Double(), nullable=True),
    sa.Column('max_score', sa.Double(), nullable=True),
    sa.Column('difficulty', sa.Double(), nullable=True),
    sa.Column('independence', sa.Double(), nullable=True),
    sa.Column('hint_count', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('evidence_confidence', sa.Double(), nullable=False),
    sa.Column('extraction_confidence', sa.Double(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supersedes_evidence_id', sa.Text(), nullable=True),
    sa.Column('item_id', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('item_revision', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("(score IS NULL AND max_score IS NULL) OR (score IS NOT NULL AND max_score IS NOT NULL AND score >= 0 AND max_score > 0 AND score <= max_score AND max_score < 'Infinity'::float8)", name=op.f('ck_learning_evidence_scores')),
    sa.CheckConstraint("result IN ('CORRECT','PARTIAL','INCORRECT','UNKNOWN')", name=op.f('ck_learning_evidence_result')),
    sa.CheckConstraint("score IS NULL OR result='UNKNOWN' OR (result='CORRECT' AND score=max_score) OR (result='INCORRECT' AND score=0) OR (result='PARTIAL' AND score>0 AND score<max_score)", name=op.f('ck_learning_evidence_score_result')),
    sa.CheckConstraint("source_type IN ('CHAT','QUIZ','MOCK_EXAM','HANDWRITTEN_ASSESSMENT','EXERCISE','CALIBRATION','MANUAL_CONFIRMATION')", name=op.f('ck_learning_evidence_source_type')),
    sa.CheckConstraint('difficulty BETWEEN 0 AND 1', name=op.f('ck_learning_evidence_difficulty')),
    sa.CheckConstraint('evidence_confidence BETWEEN 0 AND 1', name=op.f('ck_learning_evidence_evidence_confidence')),
    sa.CheckConstraint('extraction_confidence BETWEEN 0 AND 1', name=op.f('ck_learning_evidence_extraction_confidence')),
    sa.CheckConstraint('hint_count >= 0 AND (attempt_number IS NULL OR attempt_number >= 1) AND item_revision >= 1', name=op.f('ck_learning_evidence_attempts')),
    sa.CheckConstraint('independence BETWEEN 0 AND 1', name=op.f('ck_learning_evidence_independence')),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name=op.f('fk_learning_evidence_concept_id_concept')),
    sa.ForeignKeyConstraint(['learner_id', 'context_id'], ['learning_context.learner_id', 'learning_context.id'], name=op.f('fk_learning_evidence_learner_id_learning_context')),
    sa.ForeignKeyConstraint(['learner_id', 'supersedes_evidence_id'], ['learning_evidence.learner_id', 'learning_evidence.id'], name=op.f('fk_learning_evidence_learner_id_learning_evidence')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_learning_evidence_learner_id_learner')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_evidence')),
    sa.UniqueConstraint('learner_id', 'id', name=op.f('uq_learning_evidence_learner_id'))
    )
    op.create_index('idx_evidence_item', 'learning_evidence', ['learner_id', 'item_id', 'concept_id', 'source_type', 'occurred_at'], unique=False)
    op.create_index('idx_evidence_session', 'learning_evidence', ['learner_id', 'session_id', 'concept_id'], unique=False)
    op.create_index('idx_learning_evidence_learner_concept_time', 'learning_evidence', ['learner_id', 'concept_id', 'occurred_at'], unique=False)
    op.create_index('idx_learning_evidence_provenance', 'learning_evidence', ['source_type', 'source_id'], unique=False)
    op.create_index('uq_learning_evidence_source', 'learning_evidence', ['learner_id', 'source_type', 'source_id', 'concept_id'], unique=True, postgresql_where=sa.text('source_id IS NOT NULL'))
    op.create_table('misconception',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('learner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('concept_id', sa.Text(), nullable=False),
    sa.Column('context_id', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('normalized_description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','RESOLVED')", name=op.f('ck_misconception_status')),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_misconception_confidence')),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name=op.f('fk_misconception_concept_id_concept')),
    sa.ForeignKeyConstraint(['learner_id', 'context_id'], ['learning_context.learner_id', 'learning_context.id'], name=op.f('fk_misconception_learner_id_learning_context')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_misconception_learner_id_learner')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_misconception')),
    sa.UniqueConstraint('learner_id', 'concept_id', 'normalized_description', name=op.f('uq_misconception_learner_id'))
    )
    op.create_index('idx_misconception_learner_concept', 'misconception', ['learner_id', 'concept_id', 'status'], unique=False)
    op.create_table('evidence_decision',
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('learner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_source', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('ACCEPTED','PENDING','REJECTED','SUPERSEDED')", name=op.f('ck_evidence_decision_status')),
    sa.ForeignKeyConstraint(['learner_id', 'evidence_id'], ['learning_evidence.learner_id', 'learning_evidence.id'], name=op.f('fk_evidence_decision_learner_id_learning_evidence')),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], name=op.f('fk_evidence_decision_learner_id_learner')),
    sa.PrimaryKeyConstraint('sequence', name=op.f('pk_evidence_decision')),
    sa.UniqueConstraint('evidence_id', name=op.f('uq_evidence_decision_evidence_id'))
    )
    op.create_index('idx_decision_learner_status', 'evidence_decision', ['learner_id', 'status', 'sequence'], unique=False)
    op.execute("""
        CREATE FUNCTION mentra_evidence_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'learning evidence is immutable' USING ERRCODE = '23514';
        END;
        $$
    """)
    op.execute("CREATE TRIGGER trg_learning_evidence_immutable BEFORE UPDATE OR DELETE ON learning_evidence FOR EACH ROW EXECUTE FUNCTION mentra_evidence_immutable()")
    op.execute("CREATE TRIGGER trg_learning_evidence_immutable_truncate BEFORE TRUNCATE ON learning_evidence FOR EACH STATEMENT EXECUTE FUNCTION mentra_evidence_immutable()")
    # ### end Alembic commands ###


def downgrade():
    op.execute('DROP TRIGGER trg_learning_evidence_immutable_truncate ON learning_evidence')
    op.execute('DROP TRIGGER trg_learning_evidence_immutable ON learning_evidence')
    op.execute('DROP FUNCTION mentra_evidence_immutable()')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_decision_learner_status', table_name='evidence_decision')
    op.drop_table('evidence_decision')
    op.drop_index('idx_misconception_learner_concept', table_name='misconception')
    op.drop_table('misconception')
    op.drop_index('uq_learning_evidence_source', table_name='learning_evidence', postgresql_where=sa.text('source_id IS NOT NULL'))
    op.drop_index('idx_learning_evidence_provenance', table_name='learning_evidence')
    op.drop_index('idx_learning_evidence_learner_concept_time', table_name='learning_evidence')
    op.drop_index('idx_evidence_session', table_name='learning_evidence')
    op.drop_index('idx_evidence_item', table_name='learning_evidence')
    op.drop_table('learning_evidence')
    op.drop_index('idx_context_concept_learner', table_name='context_concept')
    op.drop_index('idx_context_concept_concept', table_name='context_concept')
    op.drop_table('context_concept')
    op.drop_index('uq_candidate_concept_name_context', table_name='candidate_concept')
    op.drop_index('uq_candidate_concept_global_name', table_name='candidate_concept', if_exists=True)
    op.drop_table('candidate_concept')
    op.drop_index('idx_auth_session_learner', table_name='auth_session')
    op.drop_index('idx_auth_session_expiry', table_name='auth_session')
    op.drop_table('auth_session')
    op.drop_table('mentra_account')
    op.drop_index('idx_learning_context_learner_status', table_name='learning_context')
    op.drop_table('learning_context')
    op.drop_index('idx_learner_state_learner', table_name='learner_concept_state')
    op.drop_table('learner_concept_state')
    op.drop_index('idx_learner_audit_subject', table_name='learner_audit')
    op.drop_table('learner_audit')
    op.drop_index('idx_external_identity_learner', table_name='external_identity')
    op.drop_table('external_identity')
    op.drop_index('idx_concept_relation_target', table_name='concept_relation')
    op.drop_index('idx_concept_relation_source', table_name='concept_relation')
    op.drop_table('concept_relation')
    op.drop_index('idx_redirect_target', table_name='concept_redirect')
    op.drop_table('concept_redirect')
    op.drop_index('idx_concept_alias_normalized', table_name='concept_alias')
    op.drop_table('concept_alias')
    op.drop_table('learner')
    op.drop_table('concept')
    # ### end Alembic commands ###
