"""Provider-independent read/write boundaries for other Mentra modules."""
from typing import Protocol
from .schemas import HistoryLookup, MemoryEdit


class HistoryReader(Protocol):
    def lookup(self, owner: str, current_chat: str, current_sequence: int, body: HistoryLookup, visible_ids=()) -> list[dict]: ...
    def evidence(self, owner: str, identifier: str) -> dict: ...
    def window(self, owner: str, conversation_id: str, sequence: int) -> dict: ...


class UserMemoryRepository(Protocol):
    def list(self, owner: str, query='', status=None, cursor=None, limit=30, recall=False) -> dict: ...
    def detail(self, owner: str, identifier: str) -> dict: ...
    def edit(self, owner: str, identifier: str, body: MemoryEdit) -> dict: ...
    def remove(self, owner: str, identifier: str, revision: int) -> dict: ...
