import { expect, test } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { finishOnboardingWithoutAssessment } from './profile-helpers';

const origin = 'http://127.0.0.1:18003';
test('assessment discussion and revisions precede solving, with partial answers continuing in chat', async ({page}) => {
  test.setTimeout(90_000);
  await page.goto('/register');
  await page.getByLabel('Username',{exact:true}).fill(`quiz_revision_${randomUUID().slice(0,8)}`);
  await page.getByLabel('Password',{exact:true}).fill('an isolated revision password');
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  await finishOnboardingWithoutAssessment(page);
  const headers = {Origin:'http://127.0.0.1:15173'};
  const contextResponse = await page.request.post(`${origin}/api/v1/learning-contexts`,{headers,data:{name:'Algebra',activate:true}});
  const context = await contextResponse.json();
  const setup = await page.request.post(`${origin}/api/v1/assessments`,{headers,data:{client_request_id:randomUUID(),context_id:context.context_id,topic:'Linear equations',concept_names:['Linear equations'],confirm_new_concepts:true,count:1}});
  expect(setup.ok()).toBeTruthy();
  const prepared = await setup.json();
  await page.request.delete(`${origin}/api/v1/assessments/${prepared.id}`,{headers});
  const composer = page.getByRole('textbox',{name:'Ask Mentra anything'});
  async function send(text: string) {
    await expect(composer).toBeEnabled();
    await composer.fill(text); await page.getByRole('button',{name:'Send message'}).click();
    await expect(composer).toBeEnabled();
  }
  await send('Generate a two question quiz on Linear equations');
  const cards = page.getByRole('region',{name:'Chat assessment'});
  await expect(cards).toHaveCount(1);
  const original = await cards.first().innerText();
  await send('Explain question 1 before I start');
  await expect(cards).toHaveCount(1);
  expect((await (await page.request.get(`${origin}/api/v1/assessments`)).json()).items).toHaveLength(0);
  await send('Make this assessment easier');
  await expect(cards).toHaveCount(2);
  await expect(cards.last().getByRole('heading',{name:/Revised:/})).toBeVisible();
  expect(await cards.first().innerText()).toBe(original);
  expect((await (await page.request.get(`${origin}/api/v1/assessments`)).json()).items).toHaveLength(0);
  await send('Evaluate these answers:\n1. First partial answer');
  await expect(cards.last().getByLabel('Answer 1',{exact:true})).toHaveValue('First partial answer');
  await send('Evaluate these answers:\n2. Second partial answer');
  await expect(cards.last().getByLabel('Answer 1',{exact:true})).toHaveValue('First partial answer');
  await expect(cards.last().getByLabel('Answer 2',{exact:true})).toHaveValue('Second partial answer');
  const library = (await (await page.request.get(`${origin}/api/v1/assessments`)).json()).items;
  expect(library).toHaveLength(1);
  expect((await (await page.request.get(`${origin}/api/v1/assessments/${library[0].id}/attempts`)).json())).toHaveLength(1);
  await cards.last().getByLabel('I reviewed and corrected all extracted answers').check();
  await cards.last().getByRole('button',{name:'Confirm text & submit',exact:true}).click();
  await expect(cards.last().getByText('Feedback saved and learner evidence applied.',{exact:true})).toBeVisible({timeout:20_000});
});

test('chat quiz remains a draft, typed answers grade inline, saved assessment survives chat', async ({page}) => {
  test.setTimeout(90_000);
  await page.goto('/register');
  await page.getByLabel('Username',{exact:true}).fill(`chat_quiz_${randomUUID().slice(0,8)}`);
  await page.getByLabel('Password',{exact:true}).fill('an isolated chat quiz password');
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  await finishOnboardingWithoutAssessment(page);
  const headers = {Origin:'http://127.0.0.1:15173'};
  const contextResponse = await page.request.post(`${origin}/api/v1/learning-contexts`,{headers,data:{name:'Algebra',activate:true}});
  expect(contextResponse.ok()).toBeTruthy(); const context = await contextResponse.json();
  // Establish a reviewed concept using the real assessment domain, then remove
  // that setup assessment so the library starts empty.
  const setup = await page.request.post(`${origin}/api/v1/assessments`,{headers,data:{client_request_id:randomUUID(),context_id:context.context_id,topic:'Linear equations',concept_names:['Linear equations'],confirm_new_concepts:true,count:1}});
  expect(setup.ok()).toBeTruthy(); const prepared = await setup.json();
  expect((await page.request.delete(`${origin}/api/v1/assessments/${prepared.id}`,{headers})).ok()).toBeTruthy();
  await page.getByRole('textbox',{name:'Ask Mentra anything'}).fill('Generate a two question quiz on Linear equations');
  await page.getByRole('button',{name:'Send message'}).click();
  const cards = page.getByRole('region',{name:'Chat assessment'});
  await expect(cards.first().getByRole('button',{name:'Add to assessments',exact:true})).toBeEnabled();
  expect((await (await page.request.get(`${origin}/api/v1/assessments`)).json()).items).toHaveLength(0);
  await page.reload();
  await expect(cards.first().getByRole('button',{name:'Add to assessments',exact:true})).toBeEnabled();
  await page.getByRole('textbox',{name:'Ask Mentra anything'}).fill('Evaluate these answers:\n1. First partial explanation.\n2. Second partial explanation.');
  await page.getByRole('button',{name:'Send message'}).click();
  const review = cards.last();
  await expect(review.getByText('Feedback saved and learner evidence applied.',{exact:true})).toBeVisible({timeout:20_000});
  await page.getByLabel('Upload chat files').setInputFiles({name:'answers.txt',mimeType:'text/plain',buffer:Buffer.from('1. First uploaded answer\n2. Second uploaded answer')});
  await expect(page.getByLabel('Attached files')).toContainText('answers.txt');
  await page.getByRole('textbox',{name:'Ask Mentra anything'}).fill('Evaluate this answer sheet');
  await page.getByRole('button',{name:'Send message'}).click();
  await expect(cards.last().getByLabel('Answer 1',{exact:true})).toHaveValue('First uploaded answer');
  await expect(cards.last().getByRole('button',{name:'Confirm text & submit',exact:true})).toBeDisabled();
  await cards.last().getByLabel('I reviewed and corrected all extracted answers').check();
  await cards.last().getByRole('button',{name:'Confirm text & submit',exact:true}).click();
  await expect(cards.last().getByText('Feedback saved and learner evidence applied.',{exact:true})).toBeVisible({timeout:20_000});
  await page.reload();
  await expect(cards.last().getByText('Feedback saved and learner evidence applied.',{exact:true})).toBeVisible();
  expect((await (await page.request.get(`${origin}/api/v1/assessments`)).json()).items).toHaveLength(1);
  await page.goto('/settings');
  await page.getByLabel('Always auto add assessments').check();
  await expect(page.getByLabel('Always auto add assessments')).toBeChecked();
  await expect(page.getByLabel('Always auto add assessments')).toBeEnabled();
  await page.reload();
  await expect(page.getByLabel('Always auto add assessments')).toBeChecked();
  await page.goto('/');
  await page.getByRole('textbox',{name:'Ask Mentra anything'}).fill('Generate a two question quiz on Linear equations');
  await page.getByRole('button',{name:'Send message'}).click();
  await expect(page.getByRole('region',{name:'Chat assessment'}).last().getByText('Saved to your assessments.',{exact:true})).toBeVisible();
  const chatId=page.url().split('/chat/')[1];
  expect(chatId).toBeTruthy();
  const history=await (await page.request.get(`${origin}/api/v1/conversations/${chatId}/messages`)).json();
  expect((await page.request.delete(`${origin}/api/v1/conversations/${chatId}?expected_revision=${history.conversation.revision}`,{headers})).ok()).toBeTruthy();
  expect((await (await page.request.get(`${origin}/api/v1/assessments`)).json()).items).toHaveLength(2);
});
