from typing import Protocol, ContextManager
from .schemas import StudentProfile, CalibrationAttempt, ProfileEvidence, AIEvaluation, ProfileContext


class ProfileStore(Protocol):
    def profile(self) -> StudentProfile: ...
    def save_profile(self, profile: StudentProfile) -> StudentProfile: ...
    def latest_attempt(self) -> CalibrationAttempt | None: ...
    def attempt(self, attempt_id: str) -> CalibrationAttempt | None: ...
    def save_attempt(self, attempt: CalibrationAttempt, *, new: bool = False) -> CalibrationAttempt: ...
    def evidence(self, evidence_id: str) -> ProfileEvidence | None: ...
    def source_evidence(self, source_type: str, source_id: str) -> ProfileEvidence | None: ...
    def latest_calibration_evidence(self) -> ProfileEvidence | None: ...
    def save_evidence(self, evidence: ProfileEvidence, *, new: bool = False) -> None: ...


class StudentProfileRepository(Protocol):
    def transaction(self, learner_id: str) -> ContextManager[ProfileStore]: ...


class ProfileEvaluator(Protocol):
    async def evaluate(self, evidence: ProfileEvidence, context: ProfileContext) -> AIEvaluation: ...
