from datetime import datetime
from typing import Protocol

from app.auth.models import Account, AuthenticatedIdentity


class IdentityRepository(Protocol):
    def get_account(self, username: str) -> Account | None: ...
    def register(self, username: str, password_hash: str, token_digest: str, expires_at: datetime | None, now: datetime) -> AuthenticatedIdentity: ...
    def create_account_session(self, account: Account, token_digest: str, expires_at: datetime | None, now: datetime, new_hash: str | None = None) -> AuthenticatedIdentity: ...
    def external_session(self, provider: str, subject: str, token_digest: str, expires_at: datetime, now: datetime) -> AuthenticatedIdentity: ...
    def get_session(self, token_digest: str, now: datetime) -> AuthenticatedIdentity | None: ...
    def revoke_session(self, token_digest: str, now: datetime) -> None: ...
