"""Public persistence port. Domain callers never receive SQL sessions or tables."""
from typing import Protocol
from .schemas import EventCreate, EventDraft, EventEdit, PreferencesEdit


class EventsRepository(Protocol):
    def create(self, owner: str, body: EventCreate) -> dict: ...
    def edit(self, owner: str, identifier: str, body: EventEdit) -> dict: ...
    def remove(self, owner: str, identifier: str, revision: int, operation: str) -> dict: ...
    def detail(self, owner: str, identifier: str) -> dict: ...
    def list(self, owner: str, filters: dict, cursor: str | None, limit: int) -> dict: ...
    def preferences(self, owner: str) -> dict: ...
    def set_preferences(self, owner: str, body: PreferencesEdit) -> dict: ...
    def operation(self, owner: str, identifier: str) -> dict: ...
    def replay(self, owner: str, operation: str, payload: list) -> dict | None: ...
    def sync(self, owner: str, after: int, limit: int) -> dict: ...
    def summary(self, owner: str) -> dict: ...
