from sqlalchemy import Table, Column, String, Integer, DateTime, ForeignKey, ForeignKeyConstraint, UniqueConstraint, CheckConstraint, Index, text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from app.db.metadata import metadata

student_profile = Table('student_profile', metadata,
    Column('learner_id', UUID(as_uuid=False), ForeignKey('learner.id'), primary_key=True),
    Column('details', JSONB(none_as_null=True)), Column('estimates', JSONB, nullable=False),
    Column('details_source', String(64)),
    Column('onboarding_phase', String(20), nullable=False),
    Column('calibration_status', String(20), nullable=False),
    Column('evaluation_status', String(20), nullable=False),
    Column('version', Integer, nullable=False), Column('context_version', Integer, nullable=False),
    Column('created_at', DateTime(timezone=True), nullable=False), Column('updated_at', DateTime(timezone=True), nullable=False),
    CheckConstraint('version >= 1 AND context_version >= 0', name='versions'),
    CheckConstraint("onboarding_phase IN ('information','calibration','complete')", name='phase'),
    CheckConstraint("calibration_status IN ('not_started','in_progress','skipped','completed')", name='calibration_status'),
    CheckConstraint("evaluation_status IN ('not_started','pending','evaluating','applied','failed','superseded')", name='evaluation_status'),
    CheckConstraint("(details IS NULL AND onboarding_phase='information') OR (details IS NOT NULL AND onboarding_phase<>'information')", name='required_details'),
    CheckConstraint("jsonb_typeof(estimates)='object' AND (details IS NULL OR jsonb_typeof(details)='object')", name='objects'),
    CheckConstraint('(details IS NULL) = (details_source IS NULL)', name='details_source'),
    CheckConstraint('(details IS NULL AND context_version=0) OR (details IS NOT NULL AND context_version>=1)', name='context_scope'),
)

calibration_attempt = Table('student_calibration_attempt', metadata,
    Column('id', UUID(as_uuid=False), primary_key=True),
    Column('learner_id', UUID(as_uuid=False), ForeignKey('student_profile.learner_id'), nullable=False),
    Column('context_version', Integer, nullable=False), Column('blueprint_version', String(120), nullable=False),
    Column('payload', JSONB, nullable=False), Column('status', String(20), nullable=False),
    Column('version', Integer, nullable=False), Column('created_at', DateTime(timezone=True), nullable=False),
    Column('completed_at', DateTime(timezone=True)),
    UniqueConstraint('id', 'learner_id', name='uq_student_calibration_attempt_owner'),
    CheckConstraint('version >= 1 AND context_version >= 1', name='versions'),
    CheckConstraint("status IN ('in_progress','completed','skipped','superseded')", name='status'),
    CheckConstraint("(status='in_progress') = (completed_at IS NULL)", name='completion'),
    Index('idx_student_calibration_learner', 'learner_id', 'created_at'),
    Index('uq_student_calibration_active', 'learner_id', unique=True, postgresql_where=text("status='in_progress'")),
)

profile_evidence = Table('student_profile_evidence', metadata,
    Column('id', UUID(as_uuid=False), primary_key=True),
    Column('learner_id', UUID(as_uuid=False), ForeignKey('student_profile.learner_id'), nullable=False),
    Column('calibration_attempt_id', UUID(as_uuid=False)),
    Column('context_version', Integer, nullable=False),
    Column('source_type', String(40), nullable=False), Column('source_id', String(160), nullable=False),
    Column('payload', JSONB, nullable=False), Column('status', String(20), nullable=False),
    Column('evaluation_token', UUID(as_uuid=False)), Column('claimed_at', DateTime(timezone=True)),
    Column('evaluation', JSONB(none_as_null=True)), Column('policy_version', String(80)), Column('applied_estimates', JSONB(none_as_null=True)),
    Column('created_at', DateTime(timezone=True), nullable=False),
    ForeignKeyConstraint(['calibration_attempt_id', 'learner_id'], ['student_calibration_attempt.id', 'student_calibration_attempt.learner_id'], name='fk_student_profile_evidence_attempt_owner'),
    UniqueConstraint('learner_id', 'source_type', 'source_id', name='uq_student_profile_evidence_source'),
    CheckConstraint('context_version >= 1', name='context_version'),
    CheckConstraint("source_type IN ('onboarding_calibration','assessment','interaction')", name='source_type'),
    CheckConstraint("status IN ('pending','evaluating','applied','failed','superseded')", name='status'),
    CheckConstraint("(source_type='onboarding_calibration') = (calibration_attempt_id IS NOT NULL)", name='calibration_reference'),
    CheckConstraint("status<>'evaluating' OR (evaluation_token IS NOT NULL AND claimed_at IS NOT NULL)", name='claim'),
    CheckConstraint("status<>'applied' OR (evaluation IS NOT NULL AND applied_estimates IS NOT NULL AND policy_version IS NOT NULL)", name='application'),
    Index('idx_student_profile_evidence_learner', 'learner_id', 'created_at'),
)
